#!/bin/sh
set -e

assert_user_owner() {
  if [ -e $1 ]
    then test "$(stat -c %U $1 2>/dev/null)" = "$2"
    else test "$(stat -c %U $default_file)"  = "$1"
  fi
}

assert_group_owner() {
  if [ -e $1 ]
    then test "$(stat -c %G $1 2>/dev/null)" = "$2"
    else test "$(stat -c %G $default_file)"  = "$1"
  fi
}

assert_permissions() {
  if [ -e $1 ]
    then test "$(stat -c %A $1)" = "$2"
    else test "$(stat -c %A $default_file)" = "$1"
  fi
}

assert_string_contains() {
  if [ $# -eq 0 ]; then
    false
  else
    if [ $# -eq 1 ]
      then grep -q "$1"
      else echo $1 | grep -q "$2"
    fi
  fi
}

assert_string_also_contains() {
  if [ $# -eq 1 ]; then
    false
  else
    if [ $# -eq 2 ]
      then grep "$1" | grep -q "$2"
      else echo  $1  | grep "$2" | grep -q "$3"
    fi
  fi
}

assert_also_contains() {
  if [ -f "$1" ]
    then cat "$1" | grep "$2" | grep -q "$3"
    else cat "$default_file"  | grep "$1" | grep -q "$2"
  fi
}

assert_contains() {
  if [ -f "$1" ]
    then cat "$1" | grep -q "$2"
    else cat "$default_file" | grep -q "$1"
  fi
}

assert_true () {
  if [ $1 -eq 0 ] || [ "$1" = "true" ]
    then true
    else false
  fi
}

assert_false() {
  if [ $1 -gt 0 ] || [ "$1" = "false" ]
    then true
    else false
  fi
}

assert_eq() {
  [ "$1" = "$2" ]
}

assert_dir  () {
  if [ -n "$1" ]
    then test -d "$1"
    else test -d "$default_dir"
  fi
}

assert_file () {
  if [ -n "$1" ]
    then test -f $1
    else test -f "$default_file"
  fi
}

refute_dir  () {
  if [ -n "$1" ]
    then test ! -d "$1"
    else test ! -d "$default_dir"
  fi
}

refute_file () {
  if [ -n "$1" ]
    then test ! -f $1
    else test ! -f "$default_file"
  fi
}

assert_match() {
  if [ -f "$1" ]
    then cat "$1" | grep -qE "^$2\$"
    else cat "$default_file" | grep -qE "^$1\$"
  fi
}

assert_count() {
  if [ -f "$1" ]
    then test "$(cat "$1" | grep -c "$2")" -eq $3
    else test "$(cat "$default_file" | grep -c "$1")" -eq $2
  fi
}

assert_match_count() {
  if [ -f "$1" ]
    then test "$(cat "$1" | grep -cE "^$2\$")" -eq $3
    else test "$(cat "$default_file" | grep -cE "^$1\$")" -eq $2
  fi
}
