#!/bin/sh
echo "Installing test depends."
[ -z "$DEBUG" ] && exec 1>/dev/null
set -e

if which apk > /dev/null; then
  apk --no-progress --update add git ruby ruby-dev \
    ruby-json ruby-rdoc ruby-irb ruby-io-console \
      build-base bash
else
  apt-get update
  apt-get install --no-install-recommends -y ruby \
    ruby-dev git build-essential
fi

if ! which bats > /dev/null; then
  git clone https://github.com/sstephenson/bats.git -q
  bats/install.sh /usr/local
  rm -rf \
    bats
fi
