#!/bin/bash
[ $DEBUG ] && set -x
set -e

for v in production unicorn.stderr unicorn.stdout; do
  touch /opt/discourse/log/${v}.log
  chown discourse:discourse /opt/discourse/log/$v.log
  ln -s /opt/discourse/log/${v}.log /etc/stdout.d/${v}.log
done
