#!/bin/bash
[ $DEBUG ] && set -x

set -e

export DISCOURSE_DB_HOST=${DISCOURSE_DB_HOST:-POSTGRESQL_HOST}
export DISCOURSE_DB_USER=${DISCOURSE_DB_USER:-POSTGRESQL_USER}
export DISCOURSE_DB_PORT=${DISCOURSE_DB_PORT:-POSTGRESQL_PORT}
export DISCOURSE_DB_PASSWORD=${DISCOURSE_DB_PASSWORD:-POSTGRESQL_PASS}
export DISCOURSE_REDIS_HOST=${DISCOURSE_REDIS_HOST:-REDIS_HOST}
export DISCOURSE_REDIS_PORT=${DISCOURSE_REDIS_PORT:-REDIS_PORT}

if [ -z "$DISCOURSE_SMTP_ADDRESS" ] || [ -z "$DISCOURSE_DEVELOPER_EMAILS" ]; then
  echo "You have not setup SMTP or Developer Emails, please set them up."
  exit 1
fi

tail -qf /opt/discourse/log/production.log &

touch /opt/discourse/config/discourse.conf

chown discourse:discourse /opt/discourse/config/discourse.conf

for v in $(printenv | grep -P '^DISCOURSE_' | grep -vE '^DISCOURSE_(VERSION|HOME|DATA)'); do
  echo $v | sed -r 's/^DISCOURSE_([^=]+)(.*)/\L\1\E\2/' >> \
    /opt/discourse/config/discourse.conf
done
