#!/bin/bash
[ $DEBUG ] && set -x

set -e

export DISCOURSE_DB_HOST=${POSTGRESQL_HOST:-127.0.0.1}
export DISCOURSE_DB_USER=${POSTGRESQL_USER:-admin}
export DISCOURSE_DB_PORT=${POSTGRESQL_PORT:-5432}
export DISCOURSE_DB_PASSWORD=${POSTGRESQL_PASS:-admin}
export DISCOURSE_REDIS_HOST=${REDIS_HOST:-127.0.0.1}
export DISCOURSE_REDIS_PORT=${REDIS_PORT:-6379}
export NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL:-${DISCOURSE_SMTP_USER_NAME}}

# modify notification_email in site_settings.yml
sed -i "s/noreply@unconfigured.discourse.org/$NOTIFICATION_EMAIL/" /opt/discourse/config/site_settings.yml

if [ -z "$DISCOURSE_SMTP_ADDRESS" ] || [ -z "$DISCOURSE_DEVELOPER_EMAILS" ]; then
  echo "You have not setup SMTP or Developer Emails, please set them up."
  exit 1
fi

tail -qf /opt/discourse/log/production.log &

touch /opt/discourse/config/discourse.conf

chown discourse:discourse /opt/discourse/config/discourse.conf

for v in $(printenv | grep -P '^DISCOURSE_' | grep -vE '^DISCOURSE_(VERSION|HOME|DATA)'); do
  echo $v | sed -r 's/^DISCOURSE_([^=]+)(.*)/\L\1\E\2/' >> \
    /opt/discourse/config/discourse.conf
done
