#!/bin/bash
[ $DEBUG ] && set -x
set -e

cd /opt/discourse
if [ ! -f /opt/discourse/tmp/inited ];then
 
  sleep ${PAUSE:-0}
  
  for c in tmp:create db:migrate assets:precompile assets:clean uploads:clean_up avatars:clean; do
    count=0; while [ "$count" -lt 4 ]; do
        set +e
    count=$(echo "$(($count+1))")
    if [ $count -gt 1 ]; then
      printf "\nRetrying\n"
    fi
    
    gosu discourse rake "$c" && break
    set -e
    sleep 6
    done

    if [ "$count" -gt 3 ]; then
      exit 1
    fi
  done
  touch /opt/discourse/tmp/inited
fi
