#!/bin/bash
[ $DEBUG ] && set -x
set -e

export NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL:-${DISCOURSE_SMTP_USER_NAME}}

cd /opt/discourse
if [ ! -f /opt/discourse/tmp/inited ];then
  
  # 修改notifycation_email
  sed -i -r "s/(SiteSetting.notification_email).*/\1 = \"$NOTIFICATION_EMAIL\"/" \
     /opt/discourse/db/fixtures/999_settings.rb
  sleep ${PAUSE:-0}
  
  for c in tmp:create db:migrate assets:precompile assets:clean uploads:clean_up avatars:clean; do
    count=0; while [ "$count" -lt 4 ]; do
        set +e
    count=$(echo "$(($count+1))")
    if [ $count -gt 1 ]; then
      printf "\nRetrying\n"
    fi
    
    # 如果检测到NO_ASSETS_PRECOMPILE变量就不会进行静态资源预编译工作
    if [ $NO_ASSETS_PRECOMPILE ] && [ "$c" == "assets:precompile" ];then
      gosu discourse tar xvzf /opt/statics.tar.gz -C /opt/discourse/public/
    else
      gosu discourse rake "$c" && break
    fi
    set -e
    sleep 6
    done

    if [ "$count" -gt 3 ]; then
      exit 1
    fi
  done
  touch /opt/discourse/tmp/inited
fi
