#!/bin/bash
[ $DEBUG ] && set -x
set -e

Dirs="public/assets public/images public/javascripts public/uploads log"

for d in $Dirs
do
  subdir=`dirname $d`

  if [ ! -d ${PERMANENT_DIR}/${d} ] ;then

    if [ "$subdir" == "." ];then
      [ -d ${APP_DIR}/${d} ] && mv ${APP_DIR}/${d} ${PERMANENT_DIR}/${d} || mkdir -pv ${PERMANENT_DIR}/${d}
    else
      [ ! -d ${PERMANENT_DIR}/$subdir ] && mkdir -pv ${PERMANENT_DIR}/$subdir
      [ -d ${APP_DIR}/${d} ] && mv ${APP_DIR}/${d} ${PERMANENT_DIR}/$subdir
    fi

  else
    [ -d ${APP_DIR}/${d} ] && mv ${APP_DIR}/${d} ${APP_DIR}/${d}.bak
  fi
  ln -s ${PERMANENT_DIR}/${d} ${APP_DIR}/${d}
done
